from .user_routes import user_router
from .project_routes import project_router
from .assessment_routes import assessment_router
from .question_bank_routes import question_bank_router
from .question_routes import question_router
from .question_generation_routes import question_generation_router